lib/python/setup.cfg
lib/python/src/aria/ops/definition/adapter_definition.py
lib/python/src/aria/ops/definition/attribute.py
lib/python/src/aria/ops/definition/credential_type.py
lib/python/src/aria/ops/definition/group.py
lib/python/src/aria/ops/definition/object_type.py
lib/python/src/aria/ops/definition/parameter.py
lib/python/tests/definition/test_group_definition.py
setup.py
vrealize_operations_integration_sdk/adapter_template/adapter.py
vrealize_operations_integration_sdk/describe.py

In the case where a default value was null, the null value was being turned into a literal string (i.e., `"None"`). This fixes that issue, and adds the 'Optional' type to any parameters in definitions that are allowed to be null.
In addition:
* Adds support for default values to the describe.xml generation in the tooling
* Removes `dt_type` which is deprecated/unused in Aria Ops
* In some cases the `dashboard_parameter` defaulted to `0` and in others `None`. We now standardize on `0`.
* Removes a stray character in the `adapter.py` template

Fix stringified nulls

---

lib/python/src/aria/ops/event.py
lib/python/tests/test_event.py

Originally, each of the default values for events had a comma after each declaration, which was incorrect but Python ignored. 
However, when `black` reformatted the codebase, it interpreted the commas as signifying python tuples and adjusted as such. This caused default values to become arrays when outputted to json, rather than single values. 
This PR restores correct functionality, and adds a simple test for verifying default values are working as intended.

Fix incorrect default values for events

---

lib/python/CHANGELOG.md
lib/python/setup.cfg
lib/python/src/aria/ops/suite_api_client.py

When acquiring a token, if the authorization header is set then Aria Ops Cloud will reject the request with a 401 unauthorized error. Interestingly, Aria Ops on-prem will accept the request with or without the header.

Do not send authorization header when acquiring token

---

CHANGELOG.md
vmware_aria_operations_integration_sdk/filesystem.py

Ignores .gitkeep files when generating a management pack.
Resolves VOPERATION-38186
Before:
After:

Do not include .gitkeep files in pak files

---

lib/python/CHANGELOG.md
lib/python/src/aria/ops/object.py
lib/python/tests/test_object_key.py

I was surprised this was missing.
Please think about if the behavior in each case makes sense (identifier not present vs identifier has Falsy value).

Adds an optional 'default_value' parameter to get_identifier()

---

vmware_aria_operations_integration_sdk/mp_build.py
vmware_aria_operations_integration_sdk/mp_init.py
vmware_aria_operations_integration_sdk/mp_test.py

I've wanted this for a while, decided it was simple enough to just do it.
Adds `-V` and `--version` flags to each of `mp-init`, `mp-test`, and `mp-build`.

Adds a version flag to each of the tools

---

images/base-python-adapter/swagger_server/controllers/controller.py
images/base-python-adapter/swagger_server/server_logging.py

Updates to server section of loglevels.cfg no longer requires a restart to take effect
I was sure we had a ticket for this, but I don't see it in Jira or Github.
Long run log which starts at INFO level and then switches to DEBUG after 3 collections:
```
2023-03-27 22:27:29,118 main INFO Port: 8080
2023-03-27 22:27:29,286 swagger_server.controllers.controller INFO Request: apiVersion
2023-03-27 22:27:30,414 swagger_server.controllers.controller INFO Request: definition
2023-03-27 22:27:31,87 swagger_server.controllers.controller INFO Subprocess exited before reading input.
2023-03-27 22:27:31,119 swagger_server.controllers.controller INFO Request: collect
2023-03-27 22:28:06,185 swagger_server.controllers.controller INFO Request: collect
2023-03-27 22:28:39,899 …
```

Updates to server section of loglevels.cfg no longer requires a restart to take effect

---

vmware_aria_operations_integration_sdk/collection_statistics.py

I'm open to suggestions on the text and placement, but this seemed logical enough to me.
Resolves VOPERATION-35023
Single collection:
Long run:

Add explanation of cell format to statistics output

---

CHANGELOG.md
vmware_aria_operations_integration_sdk/docker_wrapper.py
vmware_aria_operations_integration_sdk/filesystem.py

Creates a custom context to pass to the docker build image command. The custom context excludes any directory that:
* Is an top-level SDK-created directory that should not be used by the Dockerfile: `build`, ~`conf`~, `content`, `logs`, `resources`
* Is hidden (e.g., .`git`, `.idea`, etc)
* Contains a Python virtual environment
Example of running a 2-minute long-run. Times above the 2-minute mark is the time spent setting up the test, the majority of which is building the image.
Without custom context:
```
(venv-test) ❯ du -h -d 0
159M	.
(venv-test) ❯ time mp-test -c Default long-run -d 2m -i 30s
[...]
mp-test -c Default long-run -d 2m -i 30s  14.45s user 1.76s system 11% cpu 2:24.61 total
```
With custom context (Approximately 4MB):
```
(venv-test) ❯ time mp-test -c Default long-run -d …
```

Create and use a custom context for docker builds

---

vmware_aria_operations_integration_sdk/mp_test.py

When running `mp-test`, if a method (`collect`, `connect`, etc) was not selected using a command line argument and instead set interactively, the REST request to the adapter would not have a timeout set and could potentially hang forever. This ensures that the default timeout will always be set. 
After introducing a `time.sleep(60)` in the test connection method, we can select the method interactively and the request correctly times out:
```
❯ mp-test -c Default
Choose a method to test: Test Connection
Building adapter [Finished]
Waiting for adapter to start [Finished]
Running Connect [Finished]
Failed: 408 Request Timeout
Avg CPU %                   | Avg Memory Usage %         | Memory Limit | Network I/O         | Block I/O
----------------------------+----------------------------+----- …
```

Ensure timeouts are set when method is set interactively

---

vmware_aria_operations_integration_sdk/filesystem.py
vmware_aria_operations_integration_sdk/mp_build.py

Exclude any empty subdirectories in the `content` directory. This is a mitigation for the bug in Aria Ops 8.10.0-8.10.2 where an empty content/resources directory would cause all other content in the content directory to fail to import.
Resolves: #88 
Pak file contents before:
```
manifest.txt
eula.txt
resources/
resources/resources.properties
content/
content/supermetrics/
content/traversalspecs/
content/resources/
content/customgroups/
content/policies/
content/recommendations/
content/symptomdefs/
content/dashboards/
content/dashboards/testdashboard.json
content/files/
content/files/reskndmetric/
content/files/solutionconfig/
content/files/topowidget/
content/files/txtwidget/
content/alertdefs/
content/reports/
adapter.zip
```
Pak file contents after:
```
manifest.txt
eula.txt …
```

Do not include empty content/resources directory in pak file

---

CHANGELOG.md
tests/validation/test_highlights.py
vmware_aria_operations_integration_sdk/serialization.py
vmware_aria_operations_integration_sdk/validation/adapter_definition_validator.py
vmware_aria_operations_integration_sdk/validation/api_response_validation.py
vmware_aria_operations_integration_sdk/validation/describe_checks.py
vmware_aria_operations_integration_sdk/validation/endpoint_url_validator.py
vmware_aria_operations_integration_sdk/validation/highlights.py
vmware_aria_operations_integration_sdk/validation/relationship_validator.py
vmware_aria_operations_integration_sdk/validation/result.py

* When a test connection fails, it now informs the user:
* Adds a 'success' result that writes to 'validation.log', for better visibility into what tests are being run.
* Adds missing highlight tests to long-run validation -- the tests for `property-growth`, `property-value-growth`, and `event-growth` were never being run. Example 'validation.log' after successful long run:
```
SUCCESS: No abnormal object growth found
SUCCESS: No abnormal metric growth found
SUCCESS: No abnormal property growth found
SUCCESS: No abnormal property value growth found
SUCCESS: No abnormal event growth found
```
* Related: I've added #103 
Resolves #87

Improve test result visibility

---

README.md

Fix bold text for All Objects path

---

vmware_aria_operations_integration_sdk/mp_build.py

`mp-build` was copying the project directory to a temporary location when building the pack file, but then reading project files from the original location.
Removing the copy saves a good amount of time when `mp-build` initializes, because of the (potential) size of virtual environments that were included in the copy.
I verified that removing the copy does not affect the built management packs, and reduces the time it takes to start building the project. I left the temporary directory in place, as there are some writes to the current directory which are good to keep separate from the project directory (even if they are cleaned up in most cases).
Resolves #239 
Before:
After:

Remove unnecessary filesystem copy

---

vmware_aria_operations_integration_sdk/mp_build.py

Fix for ensuring the registry prompt displays only when necessary.
Resolves #238

Fix issue causing registry prompt to always appear

---

samples/snmp-template-mp/.gitignore
samples/snmp-template-mp/adapter_requirements.txt
samples/snmp-template-mp/app/adapter.py
samples/snmp-template-mp/app/pysnmp_util.py
samples/snmp-template-mp/requirements.txt

While writing the blog I found that there was too much boilerplate code in adapter.py that could be refactored, and that we needed more robust handling for tables and indices. This fixes those issues, and results in a much cleaner adapter.py.
* Update to SDK 1.0.0
* Update to Adapter Lib 0.8.0
* Refactor common code in 'adapter.py'
* Improve handing for Tables and Indices

Snmp template improvements

---

.github/workflows/aria-operations-integration-sdk.yaml
lib/java/AdapterLibrary/build.gradle.kts

Set up the Java Adapter Library tests to run with GitHub Actions.

Add Java Adapter Library CI to GitHub Actions

---

lib/java/AdapterLibrary/src/main/kotlin/com/vmware/aria/operations/Exceptions.kt
lib/java/AdapterLibrary/src/main/kotlin/com/vmware/aria/operations/NamedPipe.kt
lib/java/AdapterLibrary/src/main/kotlin/com/vmware/aria/operations/Object.kt
lib/java/AdapterLibrary/src/main/kotlin/com/vmware/aria/operations/Result.kt
lib/java/AdapterLibrary/src/main/kotlin/com/vmware/aria/operations/definition/AdapterDefinition.kt
lib/java/AdapterLibrary/src/test/java/com/vmware/aria/operations/CollectResultTest.java
lib/java/AdapterLibrary/src/test/java/com/vmware/aria/operations/EndpointResultTest.java
lib/java/AdapterLibrary/src/test/java/com/vmware/aria/operations/TestResultTest.java

Adds TestResult, EndpointResult, and CollectResult classes
Adds tests for above classes
Adds placeholder classes for PipeUtils and AdapterDefinition for use in above classes
Adds additional convenience constructor for the `Object` class
TODO: The Json serialization for `CollectResult` is not tested yet. This will likely be a separate test suite, and will require some effort to ensure all options/paths are exercised/tested.

Add TestResult, EndpointResult, and CollectResult classes

---

lib/java/AdapterLibrary/build.gradle.kts
lib/java/AdapterLibrary/src/main/kotlin/com/vmware/aria/operations/AdapterLogger.kt
lib/java/AdapterLibrary/src/test/java/com/vmware/aria/operations/LoggerTest.java

* Adds `AdapterLogger` class that simplifies setting up and creating a logger in Java adapter code
* Reads a simple configuration from the same `loglevels.cfg` file as the server and Python adapters.

Adds Adapter Logger setup functionality

---

poetry.lock

Resolves security issues reported by dependabot:
https://github.com/vmware/vmware-aria-operations-integration-sdk/security/dependabot/10
https://github.com/vmware/vmware-aria-operations-integration-sdk/security/dependabot/11

Update GitPython 3.1.32 -> 3.1.34 to resolve security vulnerabilities

---

poetry.lock

Resolves additional GitPython security issue reported by dependabot:
https://github.com/vmware/vmware-aria-operations-integration-sdk/security/dependabot/12

Update GitPython 3.1.34 -> 3.1.35 to resolve security vulnerability

---

.github/workflows/documentation.yml
docs/references/.pages
lib/java/AdapterLibrary/build.gradle.kts

* Automatically build documentation for Java Adapter Library
* Currently builds to a test branch on pull requests; these will both change once the PR is no longer a draft
Resolves #263 
Menu item:
Documentation from the menu item:

Automatically build documentation for Java Adapter Library

---

.gitignore
vmware_aria_operations_integration_sdk/containerized_adapter_rest_api.py
vmware_aria_operations_integration_sdk/mp_test.py
vmware_aria_operations_integration_sdk/project.py
vmware_aria_operations_integration_sdk/vmware_aria_operations_integration_sdk.iml

The `connections.json` file has default Suite Api Credentials. The intended behavior is that each connection either:
* Has null values for each of their local values (host, username, password), in which case they use the default values, or
* Has non-null values for each of their local values, in which case those override the defaults.
However, when a connection was loaded into memory, there was only the set of current credentials, so if the connection was ever _resaved_, then values that should have been null would be overwritten with the non-null defaults. This meant that if the defaults ever changed, connections that *should* have been using the defaults would continue to use the old defaults, as those would have been encoded into the individual connection.
In addition, there was a …

Connections with default suite api credentials now properly set the local values to none

---

lib/java/AdapterLibrary/CHANGELOG.md
lib/java/AdapterLibrary/build.gradle.kts
lib/java/AdapterLibrary/src/main/kotlin/com/vmware/aria/operations/AdapterInstance.kt
lib/java/AdapterLibrary/src/main/kotlin/com/vmware/aria/operations/Timer.kt
lib/java/AdapterLibrary/src/test/java/com/vmware/aria/operations/AdapterInstanceTest.java
lib/java/AdapterLibrary/src/test/java/com/vmware/aria/operations/TimerKtTest.java

* Prevent `JsonDecodingException` in calls to `AdapterInstance` constructor when no SuiteAPI credentials are present.
* Prevent `NoSuchElementException` in calls to `Timing.graph()` when no timers are present.

Fixes issues in Java Library

---

lib/python/CHANGELOG.md
lib/python/setup.cfg
vmware_aria_operations_integration_sdk/adapter_configurations/adapter_templates/java/new_adapter/build.gradle.kts.template
vmware_aria_operations_integration_sdk/adapter_configurations/adapter_templates/java/sample_adapter/build.gradle.kts.template
vmware_aria_operations_integration_sdk/adapter_configurations/adapter_templates/python/new_adapter/adapter_requirements.txt
vmware_aria_operations_integration_sdk/adapter_configurations/adapter_templates/python/sample_adapter/adapter_requirements.txt

* Update Python Library to version 1.0.0
* Update Python templates to use v1.0.x
* Update Java templates to use v1.0.1

Release Adapter Libraries: Python v1.0.0, Java v1.0.1

---

vmware_aria_operations_integration_sdk/adapter_configurations/adapter_templates/java/java_adapter.py
vmware_aria_operations_integration_sdk/adapter_configurations/adapter_templates/python/python_adapter.py

When selecting a template in `mp-init`, the order of the descriptions now matches the order of the templates in the selector.

Match the order that templates and their descriptions appear in mp-init

---

.github/workflows/documentation.yml
docs/get_started.md
docs/guides/container_registry_setup.md
docs/troubleshooting_and_faq/.pages
docs/troubleshooting_and_faq/container_registries.md
docs/troubleshooting_and_faq/installation.md

In particular, improve visibility on the requirement that repositories are public.
Add additional troubleshooting section that includes the case that the adapter fails because the repository is not public.
Also, improved the documentation automation, as the site was failing to build but there was no indication of that until the PR was merged and the site attempted to deploy from the `main` branch. This way the site should attempt to build on each PR, but will still only deploy once it is merged into `main`.

Improve visibility on container repository requirements

---

lib/java/AdapterLibrary/src/main/kotlin/com/vmware/aria/operations/Data.kt
lib/java/AdapterLibrary/src/main/kotlin/com/vmware/aria/operations/Object.kt
lib/java/AdapterLibrary/src/main/kotlin/com/vmware/aria/operations/Result.kt

Manually create Json for Property data (and metric data, for consistency) to remove Kotlin Serialization's 'type' attribute. It needed this to deserialize a property into either a 'NumericProperty' or 'StringProperty', as these are polymorphic types. However, we only need to serialize this data, as deserialization is handled elsewhere, so the 'type' attributes are unnecessary (but harmless).
Before:
```
{
"nonExistingObjects": [],
"relationships": [],
"result": [
{
"events": [],
"key": {
"adapterKind": "ExtendedMySQLJavaMP",
"identifiers": [],
"name": "name",
"objectKind": "TYPE"
},
"metrics": [
{
"key": "metric",
"numberValue": 9.0,
"timestamp": 1700001251136
}
],
"properties": [
{
"key": "prop1",
"numberValue": 9.0,
"timestamp": 1700001251136,
"type": …
```

Manually create Json for Metric and Property data

---

lib/java/AdapterLibrary/src/main/kotlin/com/vmware/aria/operations/AdapterInstance.kt
lib/java/AdapterLibrary/src/test/java/com/vmware/aria/operations/AdapterInstanceTest.java

Fixes an issue where deserializing a credential field with the `is_password` attribute would error, because there was no matching attribute in the `CredentialField` class.

Correctly handle the 'is_password' attribute in credential fields

---

docs/guides/adding_content.md

Issue:
The Integration SDK moved traversal spec definitions from `describe.xml` to `content/traversalSpecs/traversal.xml` but didn't update the corresponding documentation.
Resolution:
Updates the documentation to point to the correct files.

Fix documentation around adding traversals

---

docs/troubleshooting_and_faq/logs.md

There's a reference later on this page that is correct, but this reference to the directory is incorrect.

Fix typo in logs directory

---

docs/references/java_project/index.md
docs/references/mp-init.md
docs/references/python_project/index.md
vmware_aria_operations_integration_sdk/adapter_configurations/adapter_config.py

The 'images' directory structure was incorrectly created as a top-level directory, however to work correctly it needs to be a subdirectory of the 'conf' directory.
Resolves #369

Create 'images' directory structure in correct project location

---

lib/java/AdapterLibrary/build.gradle.kts
lib/java/AdapterLibrary/src/main/kotlin/com/vmware/aria/operations/AdapterInstance.kt
vmware_aria_operations_integration_sdk/adapter_configurations/adapter_templates/java/new_adapter/build.gradle.kts.template
vmware_aria_operations_integration_sdk/adapter_configurations/adapter_templates/java/sample_adapter/build.gradle.kts.template

Bump Java Library version to 1.0.4
Improve documentation around collection windows
Set new Java Projects to use the latest released version of the Java Library.
Resolves #355

Bump Java Library version to 1.0.4

---

vmware_aria_operations_integration_sdk/adapter_configurations/adapter_templates/java/new_adapter/src/main/java/Adapter.java.template
vmware_aria_operations_integration_sdk/adapter_configurations/adapter_templates/java/sample_adapter/src/main/java/Adapter.java.template
vmware_aria_operations_integration_sdk/adapter_configurations/adapter_templates/python/new_adapter/app/adapter.py.template
vmware_aria_operations_integration_sdk/adapter_configurations/adapter_templates/python/sample_adapter/app/adapter.py.template

Resolves #359 
Notes from investigation:
* OkHttp has the hanging issue, but the exact same code (as close as Ktor allows, which is quite close) using the Cio engine does not.
* In both cases, the server gets the result back in approximately the same amount of time. The hanging occurs after all other execution is finished.
* In the OkHttp case, the culprit appears to be an "OkHttp Dispatcher" thread that is still running. I've found a good number of issues related to this, but all from around ~2020 and claim be resolved in the versions we are using (e.g., https://youtrack.jetbrains.com/issue/KTOR-396)
* I tried manually closing the client, engine, dispatcher, executor, connection pool, etc - with no success. As near as I can tell, closing just the client should be sufficient, but clearly …

Explicitly exit at end of execution

---

vmware_aria_operations_integration_sdk/validation/input_validators.py

The specific error in the ticket seemed to be resolved already, but I was able to find other cases where an exception was thrown that wasn't being caught. I changed the code to catch any exception to address this.
Resolves #131

Handle all exceptions when validating images

---

samples/rest-template-mp/adapter_requirements.txt

Resolves security issue here: https://github.com/vmware/vmware-aria-operations-integration-sdk/security/dependabot/28

Update requests to 2.32

---

lib/java/AdapterLibrary/CHANGELOG.md
lib/java/AdapterLibrary/build.gradle.kts
lib/java/AdapterLibrary/src/main/kotlin/com/vmware/aria/operations/AdapterInstance.kt
lib/python/CHANGELOG.md
lib/python/setup.cfg
lib/python/src/aria/ops/adapter_instance.py
lib/python/src/aria/ops/certificate_info.py

* Add 'CertificateInfo' class to Python Adapter Library to match how the Java Adapter Library handles certificates.
* In Python and Java Adapter Libraries, add method for getting the x509 certificate that the CertificateInfo's pem string encodes
Resolves #356

Improve Certificate Handling
